import type { Metadata } from "next";
import { Poppins, Instrument_Sans } from "next/font/google";
import "./globals.css";

//components
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";

const poppins = Instrument_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
